### PR TITLE
Refactor for big data...in master branch.

### PR DESCRIPTION
**Pull request by catlook**
Partial closes issue #74

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-115d23f325/docs/cloud-big-data/v2/developer-guide/)
* The content at `user-guide` is not mapped anywhere!
* The content at `api-docs/cloud-bigdatat-v1-deprecated` is not mapped anywhere!


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* The content at `user-guide` is not mapped anywhere!
* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-38a124c08d/docs/cloud-big-data/v2/developer-guide/)


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
HULK PREVIEW

* The content at `user-guide` is not mapped anywhere!
* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-f7667491a7/docs/cloud-big-data/v2/developer-guide/)


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-62cf10e96a/docs/cloud-big-data/v2/developer-guide/)
* The content at `user-guide.json` is not mapped anywhere!


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* The content at `user-guide.json` is not mapped anywhere!
* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-7a8d426528/docs/cloud-big-data/v2/developer-guide/)


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-bigdata-v2`](https://staging.developer.rackspace.com/build-4eebfc9838/docs/cloud-big-data/v2/developer-guide/)
* The content at `user-guide.json` is not mapped anywhere!


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by cyrichardson** [comment]
Hope to fix left nav in another, insignificant PR after this one.

**Comment by cyrichardson** [comment]
Closes #74

**Pull request merged**
